"use client";
import React,{useEffect,useState} from "react";
import Link from "next/link";
import {Package,ShoppingBag,Users,TrendingUp,ArrowRight,AlertTriangle} from "lucide-react";
import {formatPrice} from "@/lib/utils";
import {useTheme} from "@/lib/theme-context";
export default function AdminDashboardPage(){const{theme}=useTheme();const[m,setM]=useState<any>({totalRevenue:0,totalOrders:0,totalCustomers:0,totalProducts:0,lowStockCount:0});const[orders,setOrders]=useState<any[]>([]);useEffect(()=>{fetch('/api/admin/analytics').then(r=>r.json()).then(d=>{if(d.metrics)setM(d.metrics);setOrders(d.recentOrders||[])}).catch(console.error)},[]);return <div className="max-w-7xl mx-auto space-y-6">
<header><h1 className="text-2xl font-black tracking-tight">Dashboard</h1><p className="text-sm text-slate-500 mt-1">A clean overview of your store performance and inventory.</p></header>
<div className="grid grid-cols-2 lg:grid-cols-4 gap-4">{[["Revenue",formatPrice(m.totalRevenue,theme.currencySymbol),TrendingUp],["Orders",m.totalOrders,ShoppingBag],["Customers",m.totalCustomers,Users],["Products",m.totalProducts,Package]].map(([label,value,Icon]:any)=><div key={label as string} className="bg-white border border-slate-200 rounded-2xl p-5 shadow-sm"><div className="flex justify-between text-xs font-bold text-slate-500"><span>{label}</span><Icon className="w-4 h-4 text-slate-400"/></div><div className="text-2xl font-black mt-3">{value}</div></div>)}</div>
<div className="grid lg:grid-cols-3 gap-5"><div className="lg:col-span-2 bg-white border border-slate-200 rounded-2xl p-6"><div className="flex justify-between items-center mb-5"><div><h2 className="font-black">Recent Orders</h2><p className="text-xs text-slate-500 mt-1">Latest order activity.</p></div><Link href="/admin/products" className="text-xs font-bold text-slate-700 flex items-center gap-1">Manage Catalog<ArrowRight className="w-3.5 h-3.5"/></Link></div><div className="overflow-x-auto"><table className="w-full text-left text-xs"><thead className="text-slate-400 uppercase border-b"><tr><th className="py-3">Order</th><th>Customer</th><th>Total</th><th>Status</th></tr></thead><tbody className="divide-y">{orders.map(o=><tr key={o.id}><td className="py-3 font-bold">{o.orderNumber}</td><td>{o.customerName}</td><td className="font-bold">{formatPrice(o.total,theme.currencySymbol)}</td><td><span className="px-2 py-1 rounded-full bg-slate-100">{o.orderStatus}</span></td></tr>)}{!orders.length&&<tr><td colSpan={4} className="py-10 text-center text-slate-400">No recent orders.</td></tr>}</tbody></table></div></div><div className="bg-white border border-slate-200 rounded-2xl p-6"><h2 className="font-black">Quick Actions</h2><div className="mt-4 space-y-2"><Link href="/admin/products" className="block p-4 rounded-xl bg-slate-950 text-white text-sm font-bold">Add / edit products</Link><Link href="/admin/settings" className="block p-4 rounded-xl border text-sm font-bold">Edit menus, banners & theme</Link><div className="p-4 rounded-xl bg-amber-50 text-amber-800 text-xs font-semibold flex gap-2"><AlertTriangle className="w-4 h-4 shrink-0"/>Low stock items: {m.lowStockCount||0}</div></div></div></div>
</div>}
